image: node

stages:
  # - build
  # - test
  - production

build:
  stage: build
  script: npm run build


test: 
  stage: test
  script : npm test


production:
  stage: production
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf login -u debanjana.maitra@gmail.com -p Ttsp1.1PCF -a api.run.pivotal.io -s master
  - ./cf push
  only:
  - master
